// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Nutrition_backend.Data;

#nullable disable

namespace Nutrition_backend.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260805013843_DropUniqueIndexAnimalRaising")]
    partial class DropUniqueIndexAnimalRaising
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Nutrition_backend.Models.AnimalDispersalReport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Barangay")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("CarabaoFemale")
                        .HasColumnType("int");

                    b.Property<int>("CarabaoMale")
                        .HasColumnType("int");

                    b.Property<int>("ChickenFemale")
                        .HasColumnType("int");

                    b.Property<int>("ChickenMale")
                        .HasColumnType("int");

                    b.Property<int>("CowFemale")
                        .HasColumnType("int");

                    b.Property<int>("CowMale")
                        .HasColumnType("int");

                    b.Property<int>("GoatFemale")
                        .HasColumnType("int");

                    b.Property<int>("GoatMale")
                        .HasColumnType("int");

                    b.Property<int>("HouseholdsReceived")
                        .HasColumnType("int");

                    b.Property<int>("PigFemale")
                        .HasColumnType("int");

                    b.Property<int>("PigMale")
                        .HasColumnType("int");

                    b.Property<int>("Purok")
                        .HasColumnType("int");

                    b.Property<string>("RecordedBy")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("RecordedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Signature")
                        .HasColumnType("longtext");

                    b.Property<int>("TotalHouseholds")
                        .HasColumnType("int");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Barangay", "Purok", "Year")
                        .IsUnique()
                        .HasDatabaseName("IX_AnimalDispersal_BarangayPurokYear");

                    b.ToTable("AnimalDispersalReports");
                });

            modelBuilder.Entity("Nutrition_backend.Models.AnimalRaisingReport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Barangay")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("CarabaoFemale")
                        .HasColumnType("int");

                    b.Property<int>("CarabaoMale")
                        .HasColumnType("int");

                    b.Property<int>("ChickenFemale")
                        .HasColumnType("int");

                    b.Property<int>("ChickenMale")
                        .HasColumnType("int");

                    b.Property<int>("CowFemale")
                        .HasColumnType("int");

                    b.Property<int>("CowMale")
                        .HasColumnType("int");

                    b.Property<int>("GoatFemale")
                        .HasColumnType("int");

                    b.Property<int>("GoatMale")
                        .HasColumnType("int");

                    b.Property<string>("HouseholdName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int>("PigFemale")
                        .HasColumnType("int");

                    b.Property<int>("PigMale")
                        .HasColumnType("int");

                    b.Property<int>("Purok")
                        .HasColumnType("int");

                    b.Property<string>("RecordedBy")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("RecordedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("AnimalRaisingReports");
                });

            modelBuilder.Entity("Nutrition_backend.Models.BackyardGardeningReport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Barangay")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("Purok")
                        .HasColumnType("int");

                    b.Property<string>("RecordedBy")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("RecordedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("TotalHouseholds")
                        .HasColumnType("int");

                    b.Property<int>("WithGarden")
                        .HasColumnType("int");

                    b.Property<int>("WithoutGarden")
                        .HasColumnType("int");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Barangay", "Purok", "Year")
                        .IsUnique()
                        .HasDatabaseName("IX_Gardening_BarangayPurokYear");

                    b.ToTable("BackyardGardeningReports");
                });

            modelBuilder.Entity("Nutrition_backend.Models.Barangay", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Barangays");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsActive = true,
                            Name = "Tintinan"
                        },
                        new
                        {
                            Id = 2,
                            IsActive = true,
                            Name = "Sample Barangay 1"
                        },
                        new
                        {
                            Id = 3,
                            IsActive = true,
                            Name = "Sample Barangay 2"
                        });
                });

            modelBuilder.Entity("Nutrition_backend.Models.CRReport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Barangay")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("Purok")
                        .HasColumnType("int");

                    b.Property<string>("RecordedBy")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("RecordedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("TotalHouseholds")
                        .HasColumnType("int");

                    b.Property<int>("WithCR")
                        .HasColumnType("int");

                    b.Property<int>("WithoutCR")
                        .HasColumnType("int");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Barangay", "Purok", "Year")
                        .IsUnique()
                        .HasDatabaseName("IX_CR_BarangayPurokYear");

                    b.ToTable("CRReports");
                });

            modelBuilder.Entity("Nutrition_backend.Models.ChildRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AgeMonths")
                        .HasColumnType("int");

                    b.Property<string>("Barangay")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<decimal>("Height")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("NutritionalStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("Purok")
                        .HasColumnType("int");

                    b.Property<int>("RecordedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("RecordedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("TargetCategory")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<decimal>("Weight")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Id");

                    b.HasIndex("RecordedBy");

                    b.ToTable("ChildRecords");
                });

            modelBuilder.Entity("Nutrition_backend.Models.IodizedSaltReport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ApprovedBy")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Barangay")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("FineSaltFidel")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("FineSaltOthers")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("FineSaltPacificBay")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("FineSaltUFC")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("NotedBy")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("OilJolly")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("OilOthers")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("OilUFC")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("PreparedBy")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("Purok")
                        .HasColumnType("int");

                    b.Property<DateTime>("RecordedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("RockSaltAtlantic")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("RockSaltFidel")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("RockSaltJay")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("RockSaltLasap")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("RockSaltOthers")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("RockSaltPagAsa")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("StoreName")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("Barangay", "Purok", "StoreName")
                        .IsUnique()
                        .HasDatabaseName("IX_IodizedSalt_BarangayPurokStore");

                    b.ToTable("IodizedSaltReports");
                });

            modelBuilder.Entity("Nutrition_backend.Models.PotableWaterReport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Barangay")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("Level1")
                        .HasColumnType("int");

                    b.Property<int>("Level2")
                        .HasColumnType("int");

                    b.Property<int>("Level3")
                        .HasColumnType("int");

                    b.Property<int>("Purok")
                        .HasColumnType("int");

                    b.Property<string>("RecordedBy")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("RecordedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("TotalHouseholds")
                        .HasColumnType("int");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Barangay", "Purok", "Year")
                        .IsUnique()
                        .HasDatabaseName("IX_PotableWater_BarangayPurokYear");

                    b.ToTable("PotableWaterReports");
                });

            modelBuilder.Entity("Nutrition_backend.Models.PregnantWomenReport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Barangay")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("HighBMI")
                        .HasColumnType("int");

                    b.Property<int>("LowBMI")
                        .HasColumnType("int");

                    b.Property<int>("NormalBMI")
                        .HasColumnType("int");

                    b.Property<int>("Purok")
                        .HasColumnType("int");

                    b.Property<string>("RecordedBy")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("RecordedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Barangay", "Purok", "Year")
                        .IsUnique()
                        .HasDatabaseName("IX_PregnantWomen_BarangayPurokYear");

                    b.ToTable("PregnantWomenReports");
                });

            modelBuilder.Entity("Nutrition_backend.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Barangay")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 8, 5, 1, 38, 42, 791, DateTimeKind.Utc).AddTicks(6835),
                            Email = "dextertenchavez@gmail.com",
                            IsActive = true,
                            PasswordHash = "$2a$12$bpNqnsk2pO8EmR7mdumID.oNto8kb6O4xdmyQWf.nZ3ZVZhJnmOmO",
                            Role = "admin",
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("Nutrition_backend.Models.VegetableSeedReport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Barangay")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("PoorFamiliesGivenSeeds")
                        .HasColumnType("int");

                    b.Property<int>("Purok")
                        .HasColumnType("int");

                    b.Property<string>("RecordedBy")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("RecordedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("SeedCount1")
                        .HasColumnType("int");

                    b.Property<int>("SeedCount2")
                        .HasColumnType("int");

                    b.Property<int>("SeedCount3")
                        .HasColumnType("int");

                    b.Property<string>("SeedType1")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("SeedType2")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("SeedType3")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("SubTotal")
                        .HasColumnType("int");

                    b.Property<int>("TotalHouseholds")
                        .HasColumnType("int");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Barangay", "Purok", "Year")
                        .IsUnique()
                        .HasDatabaseName("IX_VegetableSeed_BarangayPurokYear");

                    b.ToTable("VegetableSeedReports");
                });

            modelBuilder.Entity("Nutrition_backend.Models.VitaminAReport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ApprovedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ApprovedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Barangay")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("Months12To59")
                        .HasColumnType("int");

                    b.Property<int>("Months6To11")
                        .HasColumnType("int");

                    b.Property<int>("Purok")
                        .HasColumnType("int");

                    b.Property<string>("Quarter")
                        .HasColumnType("longtext");

                    b.Property<string>("Remarks")
                        .HasColumnType("longtext");

                    b.Property<int>("ReportedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ReportedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("UnderweightSUW")
                        .HasColumnType("int");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ApprovedByUserId");

                    b.HasIndex("ReportedByUserId");

                    b.ToTable("VitaminAReports");
                });

            modelBuilder.Entity("Nutrition_backend.Models.ChildRecord", b =>
                {
                    b.HasOne("Nutrition_backend.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("RecordedBy")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Nutrition_backend.Models.VitaminAReport", b =>
                {
                    b.HasOne("Nutrition_backend.Models.User", "ApprovedBy")
                        .WithMany()
                        .HasForeignKey("ApprovedByUserId");

                    b.HasOne("Nutrition_backend.Models.User", "ReportedBy")
                        .WithMany()
                        .HasForeignKey("ReportedByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApprovedBy");

                    b.Navigation("ReportedBy");
                });
#pragma warning restore 612, 618
        }
    }
}
